# Generated by Django 3.2.25 on 2026-09-25 13:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WealthUser',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('password_hash', models.CharField(max_length=256)),
                ('salt', models.CharField(max_length=64)),
                ('role', models.CharField(default='client', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('liability_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('amount_remaining', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='api.wealthuser')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('financial_detail', models.JSONField(default=dict)),
                ('projections', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='api.wealthuser')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('transaction_date', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.wealthuser')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('monthly_limit', models.FloatField()),
                ('current_spend', models.FloatField(default=0.0)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='api.wealthuser')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.wealthuser')),
            ],
        ),
    ]
